# Name of Server Admin
#   This parameter is overwritten by OS env JWT_SERVER_ADMIN_NAME
admin_name: admin

# Password of Server Admin
#   This parameter is overwritten by OS env JWT_SERVER_ADMIN_PASSWORD
admin_password: password

# Listen Port of Server
server_port: 8080

# Binding Address to Server
server_bind_address: "0.0.0.0"

# File Name of Output Log
#   If set empty, output log to stdout
logfile: ''

# If true, output debug level log
#   CAUTION: debug mode may output secret info into log, so you never use at production environment
debug_mode: true

db:
  type: "memory"
  connection_string: ""
  # type: "mongo"
  # connection_string: "mongodb://root:example@localhost:27017"

# Expires Time of Authorization code in OpenID Connect [sec]
oidc_auth_code_expires_time: 300

oidc_auth_code_user_login_html: "auth_code_user_login.html"