# Listen Port of Server
server_port: 8080

# Binding Address to Server
server_bind_address: "0.0.0.0"

# File Name of Output Log
#   If set empty, output log to stdout
logfile: 'jwt-server.log'

# If true, output debug level log
debug_mode: true

db:
  type: "memory"
  connection_string: ""
  # type: "mongo"
  # connection_string: "mongodb://localhost:27017"

# Name of Server Admin
#   This parameter is overwritten by OS env JWT_SERVER_ADMIN_NAME
admin_name: admin

# Password of Server Admin
#   This parameter is overwritten by OS env JWT_SERVER_ADMIN_PASSWORD
admin_password: password

# Secret key for JWT Token sigining
#   This parameter must be managed safely.
token_secret_key: 33c8bea55c2cb2bd1e6f18bf5699d5d8e6c42810c94b5ec85f909a415e03281d