# Name of Server Admin
#   This parameter is overwritten by OS env HEKATE_ADMIN_NAME
admin_name: admin

# Password of Server Admin
#   This parameter is overwritten by OS env HEKATE_ADMIN_PASSWORD
admin_password: password

# Listen Port of Server
server_port: 18443

# Binding Address to Server
server_bind_address: "0.0.0.0"

# https must be true, but may be false in the following cases
#   - SSL termination by Reverse Proxy
#   - development environment
https:
  enabled: false
  cert-file: "_data/testcerts/tls.crt"
  key-file: "_data/testcerts/tls.key"

# File Name of Output Log
#   If set empty, output log to stdout
logfile: 'hekate.log'

# If true, output debug level log
#   CAUTION: debug mode may output secret info into log, so you never use at production environment
debug_mode: true

db:
  type: "memory"
  connection_string: ""
  # type: "mongo"
  # connection_string: "mongodb://root:example@localhost:27017"

# use same params as db if comment out this
audit_db:
  type: "none"
  connection_string: ""

# Expires Time of a session for login [sec]
# This is a time from login page request to user verify
login_session_expires_time: 300

# Expires Time of Single Sign On(SSO) [sec]
sso_expires_time: 300

user_login_page_res: "_data/login"

# Interval of database garbage collector [sec]
dbgc_interval: 3600
